[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "ably>=2.0.13",
    "fastapi>=0.116.1",
    "uvicorn>=0.35.0",
]
